#! /bin/bash 

#This job automatically submits jobs every 24 hours
#Tell me you've started
SUBJECT="autojob_submission mail"
EMAIL="h.burns@noc.soton.ac.uk"
EMAILMESSAGE="Autojob summission started"

echo "$EMAILMESSAGE" | mail -s "$SUBJECT" "$EMAIL"

# Check the job has done

sleep 55000

if [ -e pickup.0008294400.data ]
  then
    next6
    EMAILMESSAGE="Day 3 fine"
    echo $EMAILMESSAGE | mail -s "SUBJECT""$EMAIL"

  else
    EMAILMESSAGE="Check Mobilis"
    echo $EMAILMESSAGE | mail -s "SUBJECT""$EMAIL"

fi

sleep 55000

if [ -e pickup.0009676800.data ]
  then
    next7
  else
    EMAILMESSAGE="Check Mobilis"
    echo $EMAILMESSAGE | mail -s "SUBJECT""$EMAIL"

fi

sleep 55000

if [ -e pickup.0011059200.data ]
  then
    next8
  else
    EMAILMESSAGE="Check Mobilis"
    echo $EMAILMESSAGE | mail -s "SUBJECT""$EMAIL"
fi
sleep 55000

if [ -e pickup.0012441600.data ]
  then
    next9
  else
    EMAILMESSAGE="Check Mobilis"
    echo $EMAILMESSAGE | mail -s "SUBJECT""$EMAIL"
fi



EMAILMESSAGE="Upto year 50 OK"

echo $EMAILMESSAGE | mail -s "SUBJECT""$EMAIL"